package com.example.final_project.database;

import android.app.Application;

import com.example.final_project.database.entities.Movie;
import com.example.final_project.database.entities.MovieDAO;
import com.example.final_project.database.entities.User;
import com.example.final_project.database.entities.UserWatchList;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Future;

public class WatchListRepository {
    private MovieDAO movieDAO;
    private UserWatchListDAO userWatchListDAO;
    private UserDAO userDAO;

    ExecutorService executor = MovieWatchlistDatabase.databaseWriteExecutor;


    private static WatchListRepository repository;

    private WatchListRepository(Application application) {
        MovieWatchlistDatabase db = MovieWatchlistDatabase.getDatabase(application);
        this.movieDAO = db.movieDAO();
        this.userDAO = db.userDAO();
        this.userWatchListDAO = db.userWatchListDAO();
    }

    public static synchronized WatchListRepository getRepository(Application application) {
        if (repository == null) {
            repository = new WatchListRepository(application);
        }
        return repository;
    }


    public void insertMovie(Movie movie, String username) {
        executor.submit(() -> {
            long movieId = movieDAO.insert(movie); // get autogenerated ID
            movie.setId((int) movieId); // if your Movie uses int IDs

            // Replace '1' with getUserByUsername(username) once user functionality is implemented
            userWatchListDAO.insert(new UserWatchList(1, movie.getId(), false, 0.0));
        });
    }

    public User getUserByUsername(String username) {
        return userDAO.getUserByUserName(username);
    }
}
